### PR TITLE
fixed yot for new 4chan API

### PR DESCRIPTION
**Pull request by tux1c**
https://github.com/mplewis/yot/issues/3

### CODE REVIEW

**Comment by ryanknutson** [comment]
Thanks! Going to try this when I get home.

**Comment by mplewis** [comment]
@tux1c and @ryanknutson, thanks for the work! I'm not maintaining this project any more. If either of you want to take over, I can post a link to your forks in my project's readme.

**Comment by tux1c** [comment]
@mplewis hahah didn't even see the other fork :S could have saved time on that

I'm thinking about continuing yot and maybe writing an ncurses based UI for it as I desperately need one for my all-CLI laptop. mind if I drop you an email if I decide to do so and then you'll include my fork in the readme?

**Comment by mplewis** [comment]
Sounds good to me!

**Pull request closed without merging**
